"""
Output Moderator — AIMO
────────────────────────
Validates every text response generated by AIMO before it reaches the student,
using the OpenAI Moderation API (omni-moderation-latest, free of charge).

WHY only moderate AIMO's output (not the student's input):
  AIMO is a mental health support chatbot. Students will — and should — share
  messages that contain distress, hopelessness, and self-harm ideation. Blocking
  those at the input layer would silence the most critical conversations.
  The real risk is the model generating harmful content in its own responses
  (e.g., self-harm instructions via prompt injection, aggressive language).

CATEGORIES CHECKED (block if score > THRESHOLD):
  - self-harm/instructions  → AIMO must never provide these (highest priority)
  - hate/threatening        → threatening language towards any group
  - harassment/threatening  → direct threats
  - violence/graphic        → graphic violence descriptions

CATEGORIES INTENTIONALLY SKIPPED:
  - self-harm / self-harm/intent → AIMO legitimately paraphrases a student's
    distress back to them empathetically ("entiendo que has pensado en hacerte
    daño..."). Blocking on these would produce false positives constantly.
  - hate / harassment / violence → too broad; empathetic reframing of anger or
    pain could trigger them in this context.

No new credentials needed — uses the existing OPENAI_API_KEY.
"""

from src.config_api import get_openai_client
from src.logger import get_logger

logger = get_logger("aimo.moderador")

# Model — omni-moderation-latest is OpenAI's current recommended moderation
# model; it is free to call regardless of request volume.
MODERATION_MODEL = "omni-moderation-latest"

# Categories whose score, if above THRESHOLD, mark the response as unsafe.
BLOCKED_CATEGORIES: set[str] = {
    "self-harm/instructions",
    "hate/threatening",
    "harassment/threatening",
    "violence/graphic",
}

# Score threshold above which a category is considered flagged.
# 0.5 balances sensitivity vs. false positives for a mental-health context.
THRESHOLD = 0.5

# Safe fallback shown to the student when moderation triggers.
# Uses LOCAL crisis resources (Cauca/Valle, Colombia) — never foreign hotlines.
FALLBACK_MENSAJE = (
    "Estoy aquí contigo y no estás solo/a en esto. Si sientes que estás en peligro "
    "o que no puedes más, por favor busca apoyo ahora mismo:\n"
    "• Línea 106 (Valle del Cauca): apoyo en crisis 24 horas, confidencial. Marca 106.\n"
    "• Hospital Universitario San José: (602) 8234508 — extensión 100 (Urgencias) "
    "o extensión 138 (Unidad de Salud Mental).\n"
    "• Servicio de psicología de la Universidad del Cauca, acompañamiento profesional "
    "confidencial:\n"
    "https://portal.unicauca.edu.co/versionP/bienestar-universitario/"
    "salud-para-estudiantes/psicologia-y-psiquiatria"
)


def moderar_salida(texto: str) -> tuple[bool, list[str]]:
    """
    Runs OpenAI Moderation on a single text string (AIMO's response).

    Parameters
    ----------
    texto : str
        The text to check — an intermediate context response or the final
        recommendations string.

    Returns
    -------
    (es_segura, categorias_flaggeadas)
        es_segura          — True if the text passes moderation.
        categorias_flaggeadas — list of blocked category names whose score
                               exceeded THRESHOLD; empty when es_segura=True.
    """
    if not texto or not texto.strip():
        return True, []

    try:
        client = get_openai_client()
    except RuntimeError:
        # OpenAI not configured — skip moderation and let the response through.
        logger.warning("OpenAI no disponible — moderación omitida")
        return True, []

    try:
        response = client.moderations.create(
            model=MODERATION_MODEL,
            input=texto,
        )
        result = response.results[0]
        scores: dict = result.category_scores.__dict__

        flagged_cats: list[str] = []
        for category in BLOCKED_CATEGORIES:
            # OpenAI returns category names with "/" replaced by "/" in the
            # attribute dict; some SDKs use "__" as separator — normalise both.
            score = _get_score(scores, category)
            if score is not None and score > THRESHOLD:
                flagged_cats.append(category)

        es_segura = len(flagged_cats) == 0

        if es_segura:
            logger.debug("Moderación OK (%.0f chars)", len(texto))
        else:
            logger.warning(
                "MODERACIÓN ACTIVADA — categorías: %s | texto (primeros 120 chars): %.120s",
                flagged_cats, texto,
            )

        return es_segura, flagged_cats

    except Exception as e:
        # On API error, fail open: let the response through but log the error.
        logger.error("Error en Moderation API: %s — respuesta liberada", e)
        return True, []


def _get_score(scores: dict, category: str) -> float | None:
    """
    Retrieves the score for a category from the category_scores object dict.
    Handles the OpenAI SDK's attribute naming (slashes → underscores or kept).
    """
    # Try direct key first (some SDK versions keep the slash)
    if category in scores:
        return scores[category]
    # Try with slash replaced by underscore (common SDK serialization)
    alt_key = category.replace("/", "_")
    if alt_key in scores:
        return scores[alt_key]
    # Try with slash replaced by double-underscore
    alt_key2 = category.replace("/", "__")
    if alt_key2 in scores:
        return scores[alt_key2]
    return None
